#!/usr/bin/env bash

set -e
set -o pipefail
# set -x
set -u

# This script contains a series of commands that, when run within a fresh Docker
# Ubuntu container, setup the environment and build project everest, all the way
# to the final (known) working test.
cd $HOME
export EVEREST_CI=1

# Known required packages
export DEBIAN_FRONTEND=noninteractive
apt-get --yes update
# Getting lots of hash sum mismatch on CI
PACKAGES="wget build-essential opam libsqlite3-dev libgmp-dev libssl-dev m4 automake git fsharp vim"
apt-get --yes install $PACKAGES || apt-get --yes install $PACKAGES || apt-get --yes install $PACKAGES

# Z3
wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip
unzip z3*
export PATH=$(pwd)/z3-4.5.0-x64-ubuntu-14.04/bin:$PATH

# Worksaround a bug in OPAM https://github.com/ocaml/opam/issues/2767
export OPAMYES=true
git clone https://github.com/project-everest/everest

# Build everything
everest/everest --yes check reset make

# The "final" test... disabled because mitls.exe doesn't quite work yet
# everest/everest test
echo "EVEREST-SUCCESS"
